package com.pr656d.cattlenotes

import com.pr656d.cattlenotes.di.DaggerAppComponent
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication

/**
 * Initialization of libraries.
 */
class CattleNotesApplication : DaggerApplication() {

    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [com.pr656d.cattlenote.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.factory().create(this)
    }
}
