package com.pr656d.cattlenotes.utils

import com.google.firebase.firestore.FirebaseFirestore

object FirestoreUtil {
    /**
     * Returns auto id generated by firestore Util.autoId().
     */
    fun autoId(): String {
        return FirebaseFirestore.getInstance()
            .collection("fakeCollection")
            .document()
            .id
    }
}